sudo: required

language: ruby

services:
  - docker

env:
  - TARGET_CONTAINER_ID=matle

before_install:
  - docker build -t hivelocityinc/mantle .
  - docker run -d --name $TARGET_CONTAINER_ID -p 80:80 hivelocityinc/mantle

script:
  - bundle exec rake
