sudo: required

language: ruby
cache: bundler

services:
  - docker

env:
  - TARGET_CONTAINER_ID=mantle

before_install:
  - docker build -t hivelocityinc/mantle .
  - docker images
  - docker run -d --name $TARGET_CONTAINER_ID -p 80:80 -p 3306:3306 hivelocityinc/mantle
  - docker ps -a

script:
  - travis_test.sh

after_success:
  - '[ "$TRAVIS_BRANCH" == master ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push hivelocityinc/mantle'
